### ISSUE TITLE
格式化宽度对字符串似乎不起作用

### ISSUE THREAD

**Issue by gitww** [bodong1987/CPPStringFormatting#1]
std::string str;
FormatLibrary::StandardLibrary::FormatTo(str, "{0,-5}", "bill");
FormatLibrary::StandardLibrary::FormatTo(str, "{0,5}", "bill");
以上内容，我这里str始终都是"bill"，没有自动适应宽度，预期结果应该是在bill的左侧或右侧出现一个空格吧
测试环境：vc2015+win10

**Comment by bodong1987** [comment]
已处理
